name: "JamCraft"
markdown: kramdown
#refresh-rate: 2
server-ip: "ch.jamcraft.net"
menu:
  left:
#    - { title: "Mod List", url: "/mods.html", icon: "results"}
  right:
    - { title: "Jenkins (KJ4IPS)", url: "http://ci.haun.guru", icon: "loop"}
    - { title: "TeamSpeak", url: "ts3server://teamspeak.jam-craft.net", icon: "microphone"}
  
#pitchin: 7081700462
